### ISSUE TITLE
Unable to restore course with active availability role

### ISSUE THREAD

**Issue by nadavkav** [moodleuulm/moodle-availability_role#1]
I have a course with one instance (usage) of availability role, used to restrict availability of a section.
Trying to restore a successful backup of the course, I am getting the following error:
"error/setting_by_name_not_found"

With more details:
Debug info: 
Error code: setting_by_name_not_found
$a contents: roles
Stack trace:
line 123 of /backup/util/plan/base_plan.class.php: base_plan_exception thrown
line 97 of /backup/util/plan/base_task.class.php: call to base_plan->get_setting()
line 106 of /backup/util/plan/base_task.class.php: call to base_task->get_setting()
line 66 of /availability/condition/role/classes/condition.php: call to base_task->get_setting_value()
line 668 of /availability/classes/tree.php: call to availability_role\condition->include_after_restore()
line 323 of /availability/classes/info.php: call to core_availability\tree->update_after_restore()
line 823 of /backup/moodle2/restore_stepslib.php: call to core_availability\info->update_after_restore()
line 34 of /backup/util/plan/restore_execution_step.class.php: call to restore_update_availability->define_execution()
line 181 of /backup/util/plan/base_task.class.php: call to restore_execution_step->execute()
line 177 of /backup/util/plan/base_plan.class.php: call to base_task->execute()
line 167 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
line 333 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
line 224 of /backup/util/ui/restore_ui.class.php: call to restore_controller->execute_plan()
line 111 of /backup/restore.php: call to restore_ui->execute()

**Comment by abias** [comment]
Hi Nadav,

thanks for resporting this issue.

I could reproduce it on one of our systems and will have a look how to resolve it soon. As we are quite busy at the moment, this might take some time.

Thanks,
Alex

**Comment by nadavkav** [comment]
Thank you Alex.
I was also too busy to dig into this and fix it at that moment, so I worked around it by disabling the recreating of availability roles in the restored from backup course.

**Comment by abias** [comment]
Hi Nadav,

we have fixed the problem and published a new version here in Github and the Moodle plugin repo.

Thanks,
Alex
