### ISSUE TITLE
Is it compatible with moodle 3.8 ?

### ISSUE THREAD

**Issue by NoxWorld258** [moodleuulm/moodle-availability_role#10]
Hello,

I was simply wondering if the plugin was compatible with the new Moodle 3.8 version ?

Also, thanks for you work.

**Comment by Kathrin84** [comment]
Hello @NoxWorld258,

thank you for your question. Just this moment I released a new version compatible for Moodle 3.8+. You can find it in the plugins repository (https://moodle.org/plugins/availability_role).

As there's nothing else to do here, I'll close this issue.

Best, Kathrin
