### ISSUE TITLE
restriction "is not"

### ISSUE THREAD

**Issue by Bambuspony** [moodleuulm/moodle-availability_role#12]
Hi,
we are on 3.9, also tested in 3.10. Works good in positive mode with "must" be...!

But if I use under restrictions "must not" i.e. role non-editing teacher (and also deleted the right to "View hidden sections - moodle/course:viewhiddensections") the non-editing teacher still sees the section/activity.
Is this the problem, that the role non-editing teacher has by desing the right to see more things/all? So the little option to hide it with the eye under restrictions, is not a real hidden, as in Edit-hide, which i can change with the above right-deletion?
Do You plan to adapt it in future?

**Comment by abias** [comment]
Hi @Bambuspony ,

I think the problem which you describe here is already answered in the README file on https://github.com/moodleuulm/moodle-availability_role#how-this-plugin-works--pitfalls.

Please check if this answers your question. 

Cheers,
Alex
