### ISSUE TITLE
Pending pull request 

### ISSUE THREAD

**Issue by rschrenk** [moodleuulm/moodle-availability_role#15]
Dear Alexander,

we had contact regarding the merger of my plugins availability_globalrole and availability_coursecatrole into availability_role. I made all required changes and set up a pull request, but it has not been accepted.

In the meanwhile it seems you have been working on the plugin, so my functionality is lost when updating.

Could you please integrate my changes?
https://github.com/moodleuulm/moodle-availability_role/pull/11

Best wishes
Robert

**Comment by abias** [comment]
Hi @rschrenk ,

I am sorry that I did not have the time to review your PR and finally merge it last year. We went through a hard phase last year where we had to pause our Moodle development and only did the most necessary things like upgrading the plugins to Moodle 3.10.

I can assure you that your PR #11 is not lost and still open and it still can be merged into the plugin.

This plugin will also soon get an additional maintainer and we will see when we can work through your useful addition in #11.

Cheers,
Alex

**Comment by rschrenk** [comment]
Hi @abias 

we will do our Moodle updates in mid July. Is there a chance to get this PR done till then?

Regards
Robert

**Comment by rschrenk** [comment]
Hi @abias 

Is there chance, that you pull my changes into the plugin now? You also developed new features, so I don't think I should work on my fork, but my changes may be of interest for all users of this plugin.

Best regards
Robert

**Comment by PM84** [comment]
I would also like to express my support for this feature. If I can help, please feel free to let me know!
