### ISSUE TITLE
Can this be adapted for faculty restrictions?

### ISSUE THREAD

**Issue by eharris1** [moodleuulm/moodle-availability_role#4]
Can this be adapted so that faculty can be restricted from editing selected modules,topic, and/or activites.

**Comment by abias** [comment]
This plugin is about availability (i.e. visibility) of an activity or topic, not about editability. 
With this plugin, you can prevent faculty from viewing certain activities and topics, but the right to edit activities and topics is still controlled by capabilities which are outside the scope of this plugin. Sorry.

**Comment by eharris1** [comment]
Thank you so much for your response.  I will keep looking.

Evelyn

Evelyn L. Harris, MBA
Director of Distance Education
Vance-Granville Community College
P.O. Box 917
Henderson, NC 27536
Phone:(252) 738-3254
Fax: 252-738-3319
harris@vgcc.edu<mailto:harris@vgcc.edu>
