### ISSUE TITLE
Missing privacy:metadata string

### ISSUE THREAD

**Issue by ewallah** [moodleuulm/moodle-availability_role#9]
Debugging: Invalid get_string() identifier: 'privacy:metadata' or component 'availability_role'.
Perhaps you are missing $string['privacy:metadata'] = ''; in availability/condition/role/lang/en/availability_role.php?

**Comment by Kathrin84** [comment]
Hi @ewallah,

thank you very much for raising this issue. We had a look at this and saw that the string was accidentally deleted with a patch.
I re-added the string with this patch: https://github.com/moodleuulm/moodle-availability_role/commit/3a65b6c259bf133cb053aceec1592dc4eeb60b35
So this is fixed and I'll close this issue.

Best, Kathrin

**Comment by ewallah** [comment]
THX
